import { Evaluation } from '@/types'
import { hydrateCommercial } from './scoring/commercial'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const DEMO_RAW = {
  username: 'demo',
  nickname: 'Demo Creator (sample data)',
  score: 72,
  tier: 'A',
  mock: true,
  followerCount: 300_000,
  followingCount: 1_500,
  totalLikes: 9_000_000,
  videoCount: 280,
  verified: false,
  region: 'US',
  avatar: undefined,
  bio: '[DEMO] Sample mid-tier fitness creator — illustrative data, not a real account.',
  computedAt: new Date().toISOString(),
  dataQuality: 'full' as const,
  formulaVersion: 'v2',
  metrics: {
    engagementRate: 7.5, avgPlays: 50_000, avgLikes: 30_000, avgComments: 2_000,
    avgShares: 3_000, likesPerVideo: 30_000, followerFollowingRatio: 200,
    recentMedianPlays: 55_000, olderMedianPlays: 40_000, playGrowth: 0.35, cvPlays: 0.8,
    daysSinceLastPost: 1, topPostPlays: 200_000, topPostLikes: 18_000,
    matureMedianPlays: 60_000, matureWeightedAvgPlays: 60_000, historicalImpliedPlays: 50_000,
    immatureVideoCount: 5, growingVideoCount: 8, likePlayRatio: 0.12,
    effectivePlaysSource: 'mature+historical' as const,
    effectivePlays: 60_000, effectiveAvgPlays: 60_000, effectivePeakPlays: 180_000,
  },
  dimensions: { reach: 68, engagement: 78, content: 71, authenticity: 82,
    momentum: 74, stability: 70, commerce: 65, monetization: 60, health: 85, influence: 68 },
  riskFlags: [],
  summary: {
    headline: '[DEMO] A-tier mid-tier fitness account sample — illustrative results, not a real valuation.',
    strengths: ['[DEMO] Illustrative 7.5% engagement rate (sample data)',
      '[DEMO] Sample 30% monthly growth figure',
      '[DEMO] Fitness niche sample CPM $22'],
    weaknesses: ['[DEMO] No verified badge — sample limitation',
      '[DEMO] US-centric reach (sample data)'],
    targetAudience: '[DEMO] Sample audience — 18-34 fitness enthusiasts',
    bestAction: '[DEMO] Sample next step: pitch 1-2 micro brand deals per month.',
  },
  verdict: '[DEMO] Tier A — sample illustrative verdict based on demo inputs.',
  advice: '[DEMO] Sample advice: post 4x/week to lock in momentum (illustrative).',
  priceAdvice: '[DEMO] Sample price range: $400 – $1,000 per brand deal (illustrative).',
  accountHealth: { overallScore: 85, shadowbanRisk: 'low' as const, shadowbanSignals: [],
    growthAnomaly: 'normal' as const, growthAnomalyReason: '[DEMO] Sample data',
    engagementAuthenticity: 95, fakeFollowerEstimate: 2, healthReasoning: '[DEMO] Sample health reasoning.' },
  contentCadence: { postingRhythm: 'daily' as const, avgPostsPerDay: 0.5, avgPostsPerWeek: 4,
    bestTimeSlots: [{ hour: 7, engagementRate: 8.2 }],
    bestWeekdays: [{ weekday: 'Monday', engagementRate: 8.5 }],
    consistencyScore: 82, cadenceAdvice: '[DEMO] 4-5 posts per week, morning uploads 7-9 AM.' },
  engagementQuality: { conversationDepth: 2.0, shareRatio: 0.05, commentLikeRatio: 0.07,
    completionRate: null, viralCoefficient: 0.15, topEngagers: [],
    qualityReasoning: '[DEMO] Sample healthy ratio.' },
  peerBenchmark: { percentile: 74, peerGroupSize: '[DEMO] sample peer group',
    benchmarks: [{ metric: '[DEMO] Engagement Rate', userValue: 7.5, peerAvg: 5.0, peerTop10: 9.0, status: 'above' as const },
      { metric: '[DEMO] Avg Plays Ratio', userValue: 16.5, peerAvg: 12, peerTop10: 24, status: 'above' as const },
      { metric: '[DEMO] 90-Day Growth', userValue: 35, peerAvg: 18, peerTop10: 45, status: 'above' as const }],
    similarCreators: [] },
  brandPotential: { brandScore: 68, estimatedCPM: 22, audienceSpendingPower: 'medium' as const,
    suitableCategories: ['[DEMO] Fitness', '[DEMO] Activewear', '[DEMO] Nutrition'],
    collaborationTypes: [{ type: '[DEMO] Product Review', fit: 0.88, expectedRevenue: '[DEMO] $400-800/post' },
      { type: '[DEMO] Tutorial Sponsorship', fit: 0.72, expectedRevenue: '[DEMO] $300-600/post' }],
    brandReasoning: '[DEMO] Sample brand reasoning.' },
  monetizationPath: { eligiblePrograms: ['tiktokShop', 'subscriptions', 'liveGifts'], nearestThreshold: null,
    estimatedMonthlyUsd: { low: 2_500, mid: 3_000, high: 3_500 },
    pathReasoning: '[DEMO] Sample path reasoning.' },
  growthPlan: {
    items: [{ priority: 'high' as const, area: '[DEMO] Content Consistency', action: '[DEMO] Post 4x/week',
      expectedImpact: '[DEMO] Reach 400K by Q2' },
      { priority: 'medium' as const, area: '[DEMO] Brand Outreach', action: '[DEMO] Pitch 3 brands',
        expectedImpact: '[DEMO] First brand deal' }],
    summary: '[DEMO] Sample growth plan summary.',
  },
  incomeEstimate: {
    monthlyTotal: { low: 2_500, mid: 3_000, high: 3_500 },
    breakdown: [
      { source: 'brand_deals' as const, label: '[DEMO] Brand Sponsorships', icon: '💰', monthlyAmount: { low: 1_400, mid: 2_000, high: 2_800 }, percentage: 38, confidence: 'high' as const, detail: '[DEMO] Sample brand deals' },
      { source: 'creator_program' as const, label: '[DEMO] Creator Fund', icon: '📺', monthlyAmount: { low: 200, mid: 300, high: 400 }, percentage: 10, confidence: 'high' as const, detail: '[DEMO] Sample creator fund' },
      { source: 'subscriptions' as const, label: '[DEMO] Subscriptions', icon: '⭐', monthlyAmount: { low: 0, mid: 0, high: 0 }, percentage: 0, confidence: 'medium' as const, detail: '[DEMO] Not activated' },
      { source: 'tiktok_shop' as const, label: '[DEMO] TikTok Shop', icon: '🛒', monthlyAmount: { low: 300, mid: 400, high: 550 }, percentage: 14, confidence: 'medium' as const, detail: '[DEMO] Sample shop' },
      { source: 'amazon_associates' as const, label: '[DEMO] Amazon Associates', icon: '📦', monthlyAmount: { low: 0, mid: 0, high: 0 }, percentage: 0, confidence: 'medium' as const, detail: '[DEMO] Not active' },
      { source: 'shopify_dtc' as const, label: '[DEMO] Shopify DTC', icon: '🧴', monthlyAmount: { low: 0, mid: 0, high: 0 }, percentage: 0, confidence: 'low' as const, detail: '[DEMO] No storefront' },
      { source: 'live_gifts' as const, label: '[DEMO] LIVE Gifts', icon: '🎁', monthlyAmount: { low: 80, mid: 150, high: 220 }, percentage: 5, confidence: 'low' as const, detail: '[DEMO] 1-2 LIVE/week' },
      { source: 'live_commerce' as const, label: '[DEMO] LIVE Commerce', icon: '🛍️', monthlyAmount: { low: 0, mid: 0, high: 0 }, percentage: 0, confidence: 'low' as const, detail: '[DEMO] Eligible at 50K+' },
    ],
    categoryCpm: 22, categoryRpm: 0.04, regionMultiplier: 1.0,
    categoryLabel: '[DEMO] Fitness', regionLabel: 'US',
    summary: '[DEMO] Sample monthly income summary.',
  },
  businessValue: {
    totalValue: { low: 45_000, mid: 75_000, high: 115_000 },
    components: [
      { label: '[DEMO] Brand Deal Annual Value', icon: '💰', amount: { low: 17_000, mid: 25_000, high: 34_000 }, percentage: 38, detail: '[DEMO] Sample brand deal annual' },
      { label: '[DEMO] Content Asset Value', icon: '🎬', amount: { low: 6_500, mid: 9_000, high: 12_000 }, percentage: 16, detail: '[DEMO] Sample content asset' },
      { label: '[DEMO] Follower Asset Value', icon: '👥', amount: { low: 4_500, mid: 7_000, high: 9_000 }, percentage: 13, detail: '[DEMO] Sample follower asset' },
      { label: '[DEMO] Monetization Capability', icon: '⚡', amount: { low: 3_500, mid: 5_000, high: 6_500 }, percentage: 9, detail: '[DEMO] Sample moncap' },
      { label: '[DEMO] IP / Brand Asset', icon: '🏆', amount: { low: 13_000, mid: 16_000, high: 20_000 }, percentage: 24, detail: '[DEMO] Sample IP' },
    ],
    summary: '[DEMO] Sample business value: $75,000 illustrative.',
  },
  brandDealPerVideo: { low: 400, mid: 700, high: 1_000, monthlyBrandPosts: 4 },
  accountProfile: { categories: ['[DEMO] Fitness', '[DEMO] Health'], personaType: '[DEMO] Mid-tier',
    postingRhythm: 'Daily', audienceRegion: 'US', contentStyle: '[DEMO] Tutorial' },
  revenueRoadmap: {
    currentMonthly: { low: 2_500, mid: 3_000, high: 3_500 },
    projections: [
      { month: 3, label: 'Month 3', revenue: { low: 3_000, mid: 3_500, high: 4_000 }, milestone: '[DEMO] Reach 400K', unlocks: ['[DEMO] Brand tier upgrade'] },
      { month: 6, label: 'Month 6', revenue: { low: 4_000, mid: 5_000, high: 6_000 }, milestone: '[DEMO] Stable brand partners', unlocks: ['[DEMO] Premium CPM'] },
      { month: 12, label: 'Month 12', revenue: { low: 6_000, mid: 7_500, high: 9_500 }, milestone: '[DEMO] 4 brand deals/month', unlocks: ['[DEMO] Multi-platform'] },
    ],
    total12Month: { low: 56_000, mid: 68_000, high: 82_000 },
    summary: '[DEMO] Sample roadmap.',
  },
  contentStrategy: {
    pillars: [
      { type: '[DEMO] Workout Tutorial', icon: '🏋️', frequency: '3x/week', expectedEngagement: '4.5-6%', examples: ['[DEMO] 30-day challenge', '[DEMO] HIIT'], why: '[DEMO] Sample pillar' },
      { type: '[DEMO] Nutrition', icon: '🥗', frequency: '1x/week', expectedEngagement: '3.5-5%', examples: ['[DEMO] Recipes'], why: '[DEMO] Sample pillar' },
      { type: '[DEMO] Motivation', icon: '💪', frequency: '1x/week', expectedEngagement: '5-7%', examples: ['[DEMO] Routine'], why: '[DEMO] Sample pillar' },
    ],
    recommendedHashtags: [
      { tag: '[DEMO] fitness', volume: 'high' as const, relevance: 0.95 },
      { tag: '[DEMO] workout', volume: 'high' as const, relevance: 0.92 },
      { tag: '[DEMO] lifestyle', volume: 'medium' as const, relevance: 0.85 },
    ],
    optimalSchedule: [
      { day: '[DEMO] Monday', time: '7:00 AM', format: '[DEMO] Tutorial' },
      { day: '[DEMO] Wednesday', time: '7:00 AM', format: '[DEMO] Tutorial' },
    ],
    videoDuration: { min: 30, max: 90, label: '30-90 seconds' },
    collaborationIdeas: [{ type: '[DEMO] Brand collab', description: '[DEMO] Sample collab', potential: 'high' as const }],
    summary: '[DEMO] Sample content strategy.',
  },
  peerRanking: { overallPercentile: 25, tierLabel: '[DEMO] Top 25%', peerGroupDescription: '[DEMO] 300K follower sample',
    rankingBreakdown: [
      { metric: '[DEMO] Engagement Rate', value: '7.5%', percentile: 74, barColor: '#00F2EA' },
      { metric: '[DEMO] Plays Ratio', value: '16.5%', percentile: 68, barColor: '#FF0050' },
      { metric: '[DEMO] Growth', value: '+35%', percentile: 81, barColor: '#22c55e' },
    ],
    insight: '[DEMO] Sample insight.' },
  brandMatching: {
    matches: [
      { category: '[DEMO] Fitness', icon: '🏋️', fitScore: 88, estimatedDealRange: { low: 400, high: 900 }, exampleBrands: ['[DEMO] Brand A', '[DEMO] Brand B'], collaborationType: '[DEMO] Product Review', reasoning: '[DEMO] Sample match' },
      { category: '[DEMO] Activewear', icon: '👟', fitScore: 78, estimatedDealRange: { low: 300, high: 700 }, exampleBrands: ['[DEMO] Brand C'], collaborationType: '[DEMO] Tutorial', reasoning: '[DEMO] Sample match' },
    ],
    totalBrandValue: { low: 35_000, mid: 50_000, high: 70_000 },
    summary: '[DEMO] Sample brand fit.',
  },
  trendAnalysis: {
    trendingTopics: [], trendingSounds: [],
    contentPredictions: [{ direction: '[DEMO] Home workouts', confidence: 80, expectedEngagement: '[DEMO] 4-6%', why: '[DEMO] Sample' }],
    bestPostTimes: [{ day: '[DEMO] Monday', hour: 7, score: 8 }],
    summary: '[DEMO] Sample trend analysis.',
  },
  commercializationAdvice: {
    directions: [{
      name: '[DEMO] Brand Sponsorships', icon: '💰', fitScore: 82, difficulty: 'medium' as const,
      estimatedMonthlyRevenue: { low: 800, mid: 1_400, high: 2_200 }, revenuePotential: 'high' as const,
      description: '[DEMO] Sample direction.',
      actionSteps: ['[DEMO] Build media kit', '[DEMO] Approach brands'],
      why: '[DEMO] Sample why.',
      prerequisites: ['[DEMO] Media kit'],
    }],
    primaryRecommendation: '[DEMO] Sample primary recommendation.',
    secondaryRecommendation: '[DEMO] Sample secondary recommendation.',
    estimatedTotalMonthly: { low: 1_000, mid: 1_800, high: 2_900 },
    summary: '[DEMO] Sample commercialization advice.',
  },
  commerceReadiness: {
    overallScore: 50, tier: 'Emerging' as const,
    summary: '[DEMO] Sample commerce readiness summary.',
    channels: [
      { source: 'tiktokShop', label: '[DEMO] TikTok Shop', icon: '🛒', monthlyAmount: { low: 300, mid: 400, high: 550 }, fitScore: 68, eligible: true, reasoning: '[DEMO] Sample channel' },
      { source: 'brandSponsorships', label: '[DEMO] Brand Sponsorships', icon: '💰', monthlyAmount: { low: 1_400, mid: 2_000, high: 2_800 }, fitScore: 82, eligible: true, reasoning: '[DEMO] Sample channel' },
    ],
    signals: [
      { label: '[DEMO] Niche strength', detected: true, weight: 0.8, detail: '[DEMO] Sample signal' },
      { label: '[DEMO] Engagement rate', detected: true, weight: 0.9, detail: '[DEMO] Sample signal' },
    ],
    productMatches: [
      { category: '[DEMO] Supplements', icon: '💪', fitScore: 85, avgOrderValue: 45, reasoning: '[DEMO] Sample match' },
    ],
    contentCommerceRatio: 0.15,
    recommendation: '[DEMO] Sample recommendation.',
  },
  calculationMetadata: {
    effectiveAvgPlays: 60_000, effectivePeakPlays: 180_000, matureVideoCount: 23,
    excludedImmatureCount: 5, excludedGrowingCount: 8, brandCpm: 22,
    engagementMultiplier: 1.8, regionMultiplier: 1.0, categoryForCpm: '[DEMO] Fitness', regionLabel: 'US',
    perVideoBrandDealMid: 700, monthlyBrandPosts: 4, likePlayRatio: 0.12, playsSource: '[DEMO] sample',
  },
} as Evaluation

// Demo 与线上同构：PMF 派生字段（commercialSnapshot/dealPricing/thirtyDayPlan）走真实引擎
export const DEMO_RESULT = hydrateCommercial(DEMO_RAW)
